/*
   This file has been generated by IDA.
   It contains local type definitions from
   exercise3_stripped.idb
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct struc_1
{
  int filename;
  int FILE;
  int time_t;
  int next;
};

/* 2 */
struct _IdaClass_struct
{
  int ida_field_1;
  float ida_field_2;
  char ida_field_3[32];
};

/* 3 */
typedef struct _IdaClass_struct IdaClass;

/* 4 */
struct _Nested_struct
{
  int x;
  int y;
  IdaClass ic;
};

/* 5 */
typedef struct _Nested_struct Nested;

