/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'exercise3'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct my_struct
{
  char *filename;
  FILE *FILEp;
  time_t time;
  my_struct *next;
};

